const KEY='taki-life-os-v3',views=['dashboard','tasks','habits','focus','notes','expenses','data'],statuses=[['todo','To Do'],['doing','Doing'],['done','Done']],day=86400000;
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const makeId=p=>p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);
const iso=o=>new Date(Date.now()+(o||0)*day).toISOString().slice(0,10);
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);
const short=d=>d?new Intl.DateTimeFormat('en',{month:'short',day:'numeric'}).format(new Date(d)):'No date';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function demo(){const t=iso(),y=iso(-1);return{theme:'light',tasks:[{id:makeId('task'),title:'Design the weekly plan',status:'todo',priority:'high',due:t},{id:makeId('task'),title:'Finish portfolio README',status:'doing',priority:'normal',due:iso(1)},{id:makeId('task'),title:'Clean downloads folder',status:'done',priority:'low',due:y}],habits:[{id:makeId('habit'),name:'Read 20 minutes',logs:{[y]:1,[t]:1}},{id:makeId('habit'),name:'Workout',logs:{[iso(-2)]:1,[y]:1}},{id:makeId('habit'),name:'No junk food',logs:{[iso(-3)]:1,[iso(-2)]:1,[y]:1,[t]:1}}],notes:[{id:makeId('note'),title:'Project Ideas',body:'Life OS roadmap:\n- Profile README\n- Habit insights\n- Better export cards',updated:Date.now()},{id:makeId('note'),title:'Daily Log',body:'Keep the dashboard simple and useful.',updated:Date.now()-60000}],expenses:[{id:makeId('exp'),label:'Course notes',amount:12,cat:'Study',date:t},{id:makeId('exp'),label:'Lunch',amount:8,cat:'Food',date:t},{id:makeId('exp'),label:'Domain idea',amount:10,cat:'Tools',date:y}],focus:{min:25,brk:5,sessions:[{id:makeId('sess'),min:25,date:iso(-2),label:'Deep work'},{id:makeId('sess'),min:50,date:y,label:'Build sprint'}]}}}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||demo()}catch{return demo()}}
let state=load(),selected=state.notes[0]?.id||null,timer={run:false,left:(state.focus?.min||25)*60,loop:null};
function save(){localStorage.setItem(KEY,JSON.stringify(state));$('#saveMsg').textContent='Saved locally';setTimeout(()=>$('#saveMsg').textContent='Offline ready',800)}
function nav(v){if(!views.includes(v))v='dashboard';$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.v===v));$('#title').textContent=v[0].toUpperCase()+v.slice(1);location.hash=v}
function render(){document.body.classList.toggle('dark',state.theme==='dark');$('#focusMin').value=state.focus.min;$('#breakMin').value=state.focus.brk;clock();dash();tasks();habits();focus();notes();expenses();summary()}
function clock(){const n=new Date();$('#dateText').textContent=new Intl.DateTimeFormat('en',{weekday:'long',month:'short',day:'numeric'}).format(n);$('#clockText').textContent=new Intl.DateTimeFormat('en',{hour:'2-digit',minute:'2-digit'}).format(n)}
function list(el,arr,map){el.replaceChildren();if(!arr.length){el.innerHTML='<p class="empty">Nothing here yet.</p>';return}el.append(...arr.map(map))}
function item(t,m,buttons){const e=document.createElement('article');e.className='item';e.innerHTML='<p><strong>'+esc(t)+'</strong></p><span class="muted">'+esc(m||'')+'</span>';if(buttons){const r=document.createElement('div');r.className='row';r.style.marginTop='10px';buttons.forEach(b=>{const x=document.createElement('button');x.className='mini';x.type='button';x.textContent=b.label;x.dataset.action=b.action;if(b.id)x.dataset.id=b.id;if(b.next)x.dataset.next=b.next;r.append(x)});e.append(r)}return e}
function dash(){const month=iso().slice(0,7),open=state.tasks.filter(t=>t.status!=='done').length,ht=state.habits.filter(h=>h.logs[iso()]).length,fm=state.focus.sessions.reduce((s,x)=>s+Number(x.min||0),0),spend=state.expenses.filter(e=>e.date.startsWith(month)).reduce((s,e)=>s+Number(e.amount||0),0);$('#metrics').innerHTML=[['Open tasks',open],['Habits today',ht+'/'+state.habits.length],['Focus minutes',fm],['Month spend',money(spend)]].map(m=>'<article class="card"><span>'+m[0]+'</span><strong>'+m[1]+'</strong></article>').join('');list($('#dashTasks'),state.tasks.filter(t=>t.status!=='done').slice(0,5),t=>item(t.title,'due '+short(t.due)));list($('#dashHabits'),state.habits.slice(0,5),h=>item(h.name,(h.logs[iso()]?'Done today':'Open today')+' - '+streak(h)+' day streak'));bars($('#focusBars'),last7().map(d=>{const mins=state.focus.sessions.filter(s=>s.date===d).reduce((a,s)=>a+Number(s.min||0),0);return[short(d),mins+'m',mins]}))}
function bars(el,rows){const max=Math.max(1,...rows.map(r=>Number(r[2])||0));el.innerHTML=rows.map(r=>'<div class="barrow"><span class="muted">'+r[0]+'</span><span class="track"><span class="fill" style="width:'+Math.max(4,(Number(r[2]||0)/max)*100)+'%"></span></span><strong>'+r[1]+'</strong></div>').join('')}
function tasks(){const b=$('#board');b.replaceChildren(...statuses.map(([s,n])=>{const c=document.createElement('section');c.className='col';const arr=state.tasks.filter(t=>t.status===s);c.innerHTML='<header><h2>'+n+'</h2><span class="pill">'+arr.length+'</span></header><div class="list"></div>';list(c.querySelector('.list'),arr,t=>item(t.title,t.priority+' - '+short(t.due),[{label:'To Do',action:'move',id:t.id,next:'todo'},{label:'Doing',action:'move',id:t.id,next:'doing'},{label:'Done',action:'move',id:t.id,next:'done'},{label:'Edit',action:'edit-task',id:t.id},{label:'Delete',action:'delete-task',id:t.id}]));return c}))}
function habits(){list($('#habitList'),state.habits,h=>{const e=document.createElement('article');e.className='item habit';e.innerHTML='<div><p><strong>'+esc(h.name)+'</strong></p><span class="muted">'+streak(h)+' day streak</span></div><div class="days"></div><div class="row"><button class="mini" data-action="delete-habit" data-id="'+h.id+'">Delete</button></div>';last7().forEach(d=>{const x=document.createElement('button');x.className='day '+(h.logs[d]?'done':'');x.textContent=short(d).split(' ')[1];x.dataset.action='toggle-habit';x.dataset.id=h.id;x.dataset.date=d;e.querySelector('.days').append(x)});return e})}
function focus(){if(!timer.left)timer.left=state.focus.min*60;$('#face').textContent=String(Math.floor(timer.left/60)).padStart(2,'0')+':'+String(timer.left%60).padStart(2,'0');list($('#sessions'),[...state.focus.sessions].reverse().slice(0,12),s=>item(s.min+' minute session',short(s.date)+' - '+(s.label||'Focus')))}
function notes(){const q=$('#noteSearch').value.toLowerCase(),arr=state.notes.filter(n=>(n.title+n.body).toLowerCase().includes(q)).sort((a,b)=>b.updated-a.updated);list($('#noteList'),arr,n=>{const e=item(n.title||'Untitled',new Date(n.updated).toLocaleString());e.dataset.note=n.id;e.classList.toggle('active-note',n.id===selected);return e});const n=state.notes.find(x=>x.id===selected)||state.notes[0];if(n){selected=n.id;$('#noteTitle').value=n.title;$('#noteBody').value=n.body;$('#deleteNote').disabled=false}else{$('#noteTitle').value='';$('#noteBody').value='';$('#deleteNote').disabled=true}}
function expenses(){list($('#expenseList'),[...state.expenses].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,18),e=>item(e.label,money(e.amount)+' - '+e.cat+' - '+short(e.date),[{label:'Delete',action:'delete-expense',id:e.id}]));const month=iso().slice(0,7),totals={};state.expenses.filter(e=>e.date.startsWith(month)).forEach(e=>totals[e.cat]=(totals[e.cat]||0)+Number(e.amount||0));bars($('#expenseBars'),Object.entries(totals).map(([k,v])=>[k,money(v),v]))}
function summary(){list($('#summary'),[['Tasks',state.tasks.length],['Habits',state.habits.length],['Notes',state.notes.length],['Expenses',state.expenses.length],['Focus sessions',state.focus.sessions.length]],x=>item(x[0],String(x[1])))}
function last7(){return[-6,-5,-4,-3,-2,-1,0].map(iso)}function streak(h){let n=0;for(let i=0;i<365;i++){if(!h.logs[iso(-i)])break;n++}return n}
function addTask(title){state.tasks.push({id:makeId('task'),title,status:'todo',priority:$('#taskPri')?.value||'normal',due:$('#taskDue')?.value||''});save();render()}
$('#nav').innerHTML=views.map(v=>'<button data-v="'+v+'">'+v[0].toUpperCase()+v.slice(1)+'</button>').join('');
$('#nav').onclick=e=>{if(e.target.dataset.v)nav(e.target.dataset.v)};
$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save();render()};
$('#quickForm').onsubmit=e=>{e.preventDefault();if($('#quickTask').value.trim()){addTask($('#quickTask').value.trim());$('#quickTask').value=''}};
$('#taskForm').onsubmit=e=>{e.preventDefault();addTask($('#taskTitle').value.trim());$('#taskTitle').value='';$('#taskDue').value=''};
$('#board').onclick=e=>{const d=e.target.dataset;if(d.action==='move'){const t=state.tasks.find(x=>x.id===d.id);if(t)t.status=d.next}if(d.action==='edit-task'){const t=state.tasks.find(x=>x.id===d.id),n=prompt('Edit task',t.title);if(n?.trim())t.title=n.trim()}if(d.action==='delete-task')state.tasks=state.tasks.filter(t=>t.id!==d.id);save();render()};
$('#habitForm').onsubmit=e=>{e.preventDefault();state.habits.push({id:makeId('habit'),name:$('#habitName').value.trim(),logs:{}});$('#habitName').value='';save();render()};
$('#habitList').onclick=e=>{const d=e.target.dataset;if(d.action==='toggle-habit'){const h=state.habits.find(x=>x.id===d.id);h.logs[d.date]?delete h.logs[d.date]:h.logs[d.date]=1}if(d.action==='delete-habit')state.habits=state.habits.filter(h=>h.id!==d.id);save();render()};
function pause(){clearInterval(timer.loop);timer.run=false}
$('#startBtn').onclick=()=>{if(timer.run)return;timer.run=true;timer.loop=setInterval(()=>{timer.left--;if(timer.left<=0){pause();state.focus.sessions.push({id:makeId('sess'),min:state.focus.min,date:iso(),label:'Focus'});timer.left=state.focus.brk*60;save()}focus();dash()},1000)};
$('#pauseBtn').onclick=pause;$('#resetBtn').onclick=()=>{pause();timer.left=state.focus.min*60;focus()};
$('#focusMin').onchange=$('#breakMin').onchange=()=>{state.focus.min=Number($('#focusMin').value||25);state.focus.brk=Number($('#breakMin').value||5);timer.left=state.focus.min*60;save();render()};
$('#newNote').onclick=()=>{const n={id:makeId('note'),title:'',body:'',updated:Date.now()};state.notes.unshift(n);selected=n.id;save();render();$('#noteTitle').focus()};
$('#noteList').onclick=e=>{const box=e.target.closest('[data-note]');if(box){selected=box.dataset.note;notes()}};$('#noteSearch').oninput=notes;
$('#noteForm').onsubmit=e=>{e.preventDefault();let n=state.notes.find(x=>x.id===selected);if(!n){n={id:makeId('note'),title:'',body:'',updated:Date.now()};state.notes.push(n);selected=n.id}n.title=$('#noteTitle').value.trim()||'Untitled';n.body=$('#noteBody').value;n.updated=Date.now();save();render()};
$('#deleteNote').onclick=()=>{state.notes=state.notes.filter(n=>n.id!==selected);selected=state.notes[0]?.id||null;save();render()};
$('#expenseDate').value=iso();$('#expenseForm').onsubmit=e=>{e.preventDefault();state.expenses.push({id:makeId('exp'),label:$('#expenseLabel').value.trim(),amount:Number($('#expenseAmount').value||0),cat:$('#expenseCat').value,date:$('#expenseDate').value||iso()});$('#expenseLabel').value='';$('#expenseAmount').value='';save();render()};
$('#expenseList').onclick=e=>{if(e.target.dataset.action==='delete-expense'){state.expenses=state.expenses.filter(x=>x.id!==e.target.dataset.id);save();render()}};
$('#exportBtn').onclick=()=>{const a=document.createElement('a'),blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});a.href=URL.createObjectURL(blob);a.download='taki-life-os-'+iso()+'.json';a.click();URL.revokeObjectURL(a.href)};
$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;state=JSON.parse(await f.text());selected=state.notes[0]?.id||null;save();render()};
$('#demoBtn').onclick=()=>{state=demo();selected=state.notes[0]?.id||null;save();render()};
$('#resetData').onclick=()=>{if(confirm('Reset all local data?')){state=demo();state.tasks=[];state.habits=[];state.notes=[];state.expenses=[];state.focus={min:25,brk:5,sessions:[]};selected=null;save();render()}};
window.onhashchange=()=>nav(location.hash.slice(1));nav(location.hash.slice(1)||'dashboard');render();setInterval(clock,30000);
